---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.1
  name: crdcleanuppolicies.policies.kreepy.jays-lab.de
spec:
  group: policies.kreepy.jays-lab.de
  names:
    kind: CRDCleanupPolicy
    listKind: CRDCleanupPolicyList
    plural: crdcleanuppolicies
    singular: crdcleanuppolicy
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CRDCleanupPolicy is the Schema for the crdcleanuppolicies API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CRDCleanupPolicySpec defines the desired state of CRDCleanupPolicy.
            properties:
              crdsversions:
                description: |-
                  CRDsVersions is a list of names and apiVersions of CustomResourceDefinitions that the operator should delete.
                  Only the name of the CRD is required.
                items:
                  properties:
                    name:
                      description: Name is the name of the CustomResourceDefinition
                        that the operator should delete.
                      type: string
                    version:
                      description: Version is the apiVersion of the CustomResourceDefinition
                        that the operator should delete.
                      type: string
                  required:
                  - name
                  type: object
                type: array
            type: object
          status:
            description: CRDCleanupPolicyStatus defines the observed state of CRDCleanupPolicy.
            properties:
              nonExistentCrds:
                description: NonExistentCRDs is a list of names of CRDs that were
                  not existing while processing.
                items:
                  type: string
                type: array
              processedCrds:
                description: ProcessedCRDs is a list of names of CRDs that have already
                  been processed by the operator.
                items:
                  type: string
                type: array
              remainingCrds:
                description: RemainingCRDs is a list of names of CRDs that are yet
                  to be processed.
                items:
                  type: string
                type: array
              statusMessage:
                description: StatusMessage provides information about the current
                  state of the cleanup process.
                type: string
            required:
            - nonExistentCrds
            - processedCrds
            - remainingCrds
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
